---
dontChroot: true
timeout: 120
script:
  - command: "chroot ${ROOT} /bin/bash -c 'rm -f /etc/mkinitcpio.conf.d/archiso.conf && pacman -S --noconfirm linux 2>/dev/null || true'"
    timeout: 60
    verbose: true
i18n:
    name: "Reinstalling kernel in target system"
