---
dontChroot: true
timeout: 120
script:
  - command: "chroot ${ROOT} /bin/bash -c 'pacman-key --init && pacman-key --populate && pacman -Syu archlinux-keyring --noconfirm && pacman-key --populate && pacman -Syu --noconfirm linux 2>/dev/null || true'"
    timeout: 60000000
    verbose: true
i18n:
    name: "Upgrading your system. This may take a while."
