---
showSupportUrl:         false
showKnownIssuesUrl:     false
showReleaseNotesUrl:    true
showDonateUrl:          false

requirements:
    requiredStorage:    10.0
    requiredRam:        2.0
    check:
        - storage
        - ram
        - power
        - internet
        - root
        - screen
    required:
        - ram
        - storage

geoip:
    style:    "none"
