---
modules-search: [ local ]

instances:
- id:       fix-kernel-perms
  module:   shellprocess
  config:   fix-kernel-perms.conf
- id:       enable-pipewire
  module:   shellprocess
  config:   enable-pipewire.conf
- id:       ollama-setup
  module:   shellprocess
  config:   ollama-setup.conf
- id:       ollama-pull
  module:   shellprocess
  config:   ollama-pull.conf
- id:       ai-welcome
  module:   notesqml
  config:   ai-welcome.conf

sequence:
- show:
  - welcome
  - notesqml@ai-welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - locale
  - keyboard
  - localecfg
  - fstab
  - shellprocess@fix-kernel-perms
  - initcpiocfg
  - initcpio
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - bootloader
  - grubcfg
  - packages
  - shellprocess@enable-pipewire
  - shellprocess@ollama-setup
  - umount
- show:
  - finished

branding: tails1154os

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
